document.twitchRes = JSON.stringify({
  "streams": [{
    "_id": 20402950544,
    "game": "League of Legends",
    "viewers": 21383,
    "created_at": "2016-03-24T11:08:04Z",
    "video_height": 720,
    "average_fps": 60.0211528292,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/imaqtpie"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_imaqtpie-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_imaqtpie-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_imaqtpie-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_imaqtpie-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": " [Imaqtpie - Challenger ADC] duo queue with dominate we gonna have some good games of solo queue",
      "broadcaster_language": "en",
      "display_name": "imaqtpie",
      "game": "League of Legends",
      "language": "en",
      "_id": 24991333,
      "name": "imaqtpie",
      "created_at": "2011-09-22T13:10:14Z",
      "updated_at": "2016-03-24T13:30:20Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/imaqtpie-profile_image-8efb10b7bed60d76-300x300.jpeg",
      "banner": null,
      "video_banner": null,
      "background": null,
      "profile_banner": null,
      "profile_banner_background_color": null,
      "partner": true,
      "url": "https://secure.twitch.tv/imaqtpie",
      "views": 123269603,
      "followers": 1085979,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/imaqtpie",
        "follows": "http://api.twitch.tv/kraken/channels/imaqtpie/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/imaqtpie/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/imaqtpie/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/imaqtpie",
        "features": "http://api.twitch.tv/kraken/channels/imaqtpie/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/imaqtpie/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/imaqtpie/editors",
        "teams": "http://api.twitch.tv/kraken/channels/imaqtpie/teams",
        "videos": "http://api.twitch.tv/kraken/channels/imaqtpie/videos"
      }
    }
  }, {
    "_id": 20402257600,
    "game": "Dota 2",
    "viewers": 14103,
    "created_at": "2016-03-24T09:56:31Z",
    "video_height": 720,
    "average_fps": 60.7703281027,
    "delay": 120,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/esl_joindotared"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_esl_joindotared-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_esl_joindotared-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_esl_joindotared-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_esl_joindotared-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "VG.R vs Wings Gaming - ESL One CN Finals w/ @TobiWanDOTA \u0026 @Heen1337",
      "broadcaster_language": "en",
      "display_name": "esl_joindotared",
      "game": "Dota 2",
      "language": "en",
      "_id": 82312665,
      "name": "esl_joindotared",
      "created_at": "2015-02-10T14:54:42Z",
      "updated_at": "2016-03-24T13:30:25Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/esl_joindotared-profile_image-cc4669ca1797cae2-300x300.png",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/esl_joindotared-channel_offline_image-36bd66f9d692366c-1920x1080.png",
      "background": null,
      "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/esl_joindotared-profile_banner-b968b6e5a241fc99-480.png",
      "profile_banner_background_color": null,
      "partner": true,
      "url": "https://secure.twitch.tv/esl_joindotared",
      "views": 8143929,
      "followers": 32765,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/esl_joindotared",
        "follows": "http://api.twitch.tv/kraken/channels/esl_joindotared/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/esl_joindotared/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/esl_joindotared/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/esl_joindotared",
        "features": "http://api.twitch.tv/kraken/channels/esl_joindotared/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/esl_joindotared/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/esl_joindotared/editors",
        "teams": "http://api.twitch.tv/kraken/channels/esl_joindotared/teams",
        "videos": "http://api.twitch.tv/kraken/channels/esl_joindotared/videos"
      }
    }
  }, {
    "_id": 20374732704,
    "game": "Super Mario Galaxy",
    "viewers": 13718,
    "created_at": "2016-03-22T22:56:15Z",
    "video_height": 720,
    "average_fps": 60.0100857287,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/ungespielt"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_ungespielt-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_ungespielt-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_ungespielt-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_ungespielt-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "30 TAGE LIVESTREAM MARATHON #ungestreamt",
      "broadcaster_language": "de",
      "display_name": "ungespielt",
      "game": "Super Mario Galaxy",
      "language": "de",
      "_id": 36983084,
      "name": "ungespielt",
      "created_at": "2012-10-17T15:56:04Z",
      "updated_at": "2016-03-24T13:30:24Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/ungespielt-profile_image-29328257f994985d-300x300.jpeg",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/ungespielt-channel_offline_image-529c8463e5dbea80-1920x1080.png",
      "background": null,
      "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/ungespielt-profile_banner-6d42206c0c973068-480.png",
      "profile_banner_background_color": null,
      "partner": true,
      "url": "https://secure.twitch.tv/ungespielt",
      "views": 13656090,
      "followers": 632916,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/ungespielt",
        "follows": "http://api.twitch.tv/kraken/channels/ungespielt/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/ungespielt/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/ungespielt/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/ungespielt",
        "features": "http://api.twitch.tv/kraken/channels/ungespielt/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/ungespielt/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/ungespielt/editors",
        "teams": "http://api.twitch.tv/kraken/channels/ungespielt/teams",
        "videos": "http://api.twitch.tv/kraken/channels/ungespielt/videos"
      }
    }
  }, {
    "_id": 20403552080,
    "game": "Dark Souls III",
    "viewers": 13623,
    "created_at": "2016-03-24T12:02:17Z",
    "video_height": 720,
    "average_fps": 60.5714285714,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/cohhcarnage"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_cohhcarnage-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_cohhcarnage-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_cohhcarnage-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_cohhcarnage-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "[PC/NA] Dark Souls 3 - More Deus Ex: HR Soon(tm)!  - !4year",
      "broadcaster_language": "en",
      "display_name": "CohhCarnage",
      "game": "Dark Souls III",
      "language": "en",
      "_id": 26610234,
      "name": "cohhcarnage",
      "created_at": "2011-12-06T18:20:34Z",
      "updated_at": "2016-03-24T13:30:45Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/cohhcarnage-profile_image-170de4e7853fde48-300x300.png",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/cohhcarnage-channel_offline_image-f846394d26e4c503-1920x1080.png",
      "background": null,
      "profile_banner": null,
      "profile_banner_background_color": null,
      "partner": true,
      "url": "https://secure.twitch.tv/cohhcarnage",
      "views": 29347503,
      "followers": 559387,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/cohhcarnage",
        "follows": "http://api.twitch.tv/kraken/channels/cohhcarnage/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/cohhcarnage/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/cohhcarnage/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/cohhcarnage",
        "features": "http://api.twitch.tv/kraken/channels/cohhcarnage/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/cohhcarnage/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/cohhcarnage/editors",
        "teams": "http://api.twitch.tv/kraken/channels/cohhcarnage/teams",
        "videos": "http://api.twitch.tv/kraken/channels/cohhcarnage/videos"
      }
    }
  }, {
    "_id": 20402125568,
    "game": "Dota 2",
    "viewers": 11739,
    "created_at": "2016-03-24T09:41:36Z",
    "video_height": 720,
    "average_fps": 60.5714285714,
    "delay": 120,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/esl_ruhub_dota2_ru"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_esl_ruhub_dota2_ru-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_esl_ruhub_dota2_ru-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_esl_ruhub_dota2_ru-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_esl_ruhub_dota2_ru-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "IG Vitality vs. Vici Gaming Reborn, ESL MANILA China Qual by @LexRUHUB",
      "broadcaster_language": "ru",
      "display_name": "esl_RuHub_dota2_ru",
      "game": "Dota 2",
      "language": "ru",
      "_id": 83920024,
      "name": "esl_ruhub_dota2_ru",
      "created_at": "2015-02-27T18:30:50Z",
      "updated_at": "2016-03-24T13:16:18Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/esl_ruhub_dota2_ru-profile_image-0cc186f3885f887e-300x300.png",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/esl_ruhub_dota2_ru-channel_offline_image-0edabfcc09a4298a-1920x1080.png",
      "background": null,
      "profile_banner": null,
      "profile_banner_background_color": null,
      "partner": true,
      "url": "https://secure.twitch.tv/esl_ruhub_dota2_ru",
      "views": 744974,
      "followers": 14782,
      "_links": {
        "self": "https://api.twitch.tv/kraken/channels/esl_ruhub_dota2_ru",
        "follows": "https://api.twitch.tv/kraken/channels/esl_ruhub_dota2_ru/follows",
        "commercial": "https://api.twitch.tv/kraken/channels/esl_ruhub_dota2_ru/commercial",
        "stream_key": "https://api.twitch.tv/kraken/channels/esl_ruhub_dota2_ru/stream_key",
        "chat": "https://api.twitch.tv/kraken/chat/esl_ruhub_dota2_ru",
        "features": "https://api.twitch.tv/kraken/channels/esl_ruhub_dota2_ru/features",
        "subscriptions": "https://api.twitch.tv/kraken/channels/esl_ruhub_dota2_ru/subscriptions",
        "editors": "https://api.twitch.tv/kraken/channels/esl_ruhub_dota2_ru/editors",
        "teams": "https://api.twitch.tv/kraken/channels/esl_ruhub_dota2_ru/teams",
        "videos": "https://api.twitch.tv/kraken/channels/esl_ruhub_dota2_ru/videos"
      }
    }
  }, {
    "_id": 20402577520,
    "game": "League of Legends",
    "viewers": 10487,
    "created_at": "2016-03-24T10:30:10Z",
    "video_height": 1080,
    "average_fps": 30.2857142857,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/garenatw"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_garenatw-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_garenatw-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_garenatw-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_garenatw-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "《LOL》2016 LMS 春季聯賽 W9D1   19:00",
      "broadcaster_language": "zh",
      "display_name": "GarenaTW",
      "game": "League of Legends",
      "language": "zh-tw",
      "_id": 28462004,
      "name": "garenatw",
      "created_at": "2012-02-24T07:03:33Z",
      "updated_at": "2016-03-24T13:30:38Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/garenatw-profile_image-85f32c0eaad8b48e-300x300.jpeg",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/garenatw-channel_offline_image-41629b499a455465-1920x1080.jpeg",
      "background": null,
      "profile_banner": null,
      "profile_banner_background_color": null,
      "partner": true,
      "url": "https://secure.twitch.tv/garenatw",
      "views": 139413061,
      "followers": 240867,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/garenatw",
        "follows": "http://api.twitch.tv/kraken/channels/garenatw/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/garenatw/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/garenatw/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/garenatw",
        "features": "http://api.twitch.tv/kraken/channels/garenatw/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/garenatw/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/garenatw/editors",
        "teams": "http://api.twitch.tv/kraken/channels/garenatw/teams",
        "videos": "http://api.twitch.tv/kraken/channels/garenatw/videos"
      }
    }
  }, {
    "_id": 20400682976,
    "game": "Hearthstone: Heroes of Warcraft",
    "viewers": 9369,
    "created_at": "2016-03-24T06:46:27Z",
    "video_height": 1080,
    "average_fps": 30,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/p4wnyhof"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_p4wnyhof-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_p4wnyhof-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_p4wnyhof-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_p4wnyhof-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "Brawl and Screw Malygos Roulette (it betrayed me) - Join my awesome community!",
      "broadcaster_language": "en",
      "display_name": "P4wnyhof",
      "game": "Hearthstone: Heroes of Warcraft",
      "language": "en",
      "_id": 71672341,
      "name": "p4wnyhof",
      "created_at": "2014-09-21T15:03:12Z",
      "updated_at": "2016-03-24T13:30:13Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/p4wnyhof-profile_image-b30742b7cdd4c4d0-300x300.jpeg",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/p4wnyhof-channel_offline_image-7f7015422b4cf91a-1920x1080.png",
      "background": null,
      "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/p4wnyhof-profile_banner-5c2d5d739bea0bb2-480.png",
      "profile_banner_background_color": null,
      "partner": true,
      "url": "https://secure.twitch.tv/p4wnyhof",
      "views": 4928799,
      "followers": 117691,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/p4wnyhof",
        "follows": "http://api.twitch.tv/kraken/channels/p4wnyhof/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/p4wnyhof/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/p4wnyhof/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/p4wnyhof",
        "features": "http://api.twitch.tv/kraken/channels/p4wnyhof/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/p4wnyhof/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/p4wnyhof/editors",
        "teams": "http://api.twitch.tv/kraken/channels/p4wnyhof/teams",
        "videos": "http://api.twitch.tv/kraken/channels/p4wnyhof/videos"
      }
    }
  }, {
    "_id": 20402843680,
    "game": "Hearthstone: Heroes of Warcraft",
    "viewers": 8290,
    "created_at": "2016-03-24T10:58:14Z",
    "video_height": 1080,
    "average_fps": 60,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/savjz"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_savjz-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_savjz-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_savjz-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_savjz-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "FeelsShaMan",
      "broadcaster_language": "en",
      "display_name": "Savjz",
      "game": "Hearthstone: Heroes of Warcraft",
      "language": "fi",
      "_id": 43131877,
      "name": "savjz",
      "created_at": "2013-05-03T12:27:19Z",
      "updated_at": "2016-03-24T13:30:25Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/savjz-profile_image-fcb7a4314f7a9e31-300x300.jpeg",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/savjz-channel_offline_image-d5f934a3be298830-1920x1080.png",
      "background": null,
      "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/savjz-profile_banner-5478456019f9dd73-480.png",
      "profile_banner_background_color": null,
      "partner": true,
      "url": "https://secure.twitch.tv/savjz",
      "views": 8932428,
      "followers": 170048,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/savjz",
        "follows": "http://api.twitch.tv/kraken/channels/savjz/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/savjz/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/savjz/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/savjz",
        "features": "http://api.twitch.tv/kraken/channels/savjz/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/savjz/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/savjz/editors",
        "teams": "http://api.twitch.tv/kraken/channels/savjz/teams",
        "videos": "http://api.twitch.tv/kraken/channels/savjz/videos"
      }
    }
  }, {
    "_id": 20401041328,
    "game": "League of Legends",
    "viewers": 7900,
    "created_at": "2016-03-24T07:31:23Z",
    "video_height": 1080,
    "average_fps": 48.8,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/asiagodtonegg3be0"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_asiagodtonegg3be0-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_asiagodtonegg3be0-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_asiagodtonegg3be0-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_asiagodtonegg3be0-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "GO master台服第一重返農藥  五路皆神 想虐就虐 EASY",
      "broadcaster_language": "zh",
      "display_name": "asiagodtonegg3be0",
      "game": "League of Legends",
      "language": "en",
      "_id": 43177431,
      "name": "asiagodtonegg3be0",
      "created_at": "2013-05-04T15:56:38Z",
      "updated_at": "2016-03-24T13:16:16Z",
      "delay": null,
      "logo": null,
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/asiagodtonegg3be0-channel_offline_image-9a70cea2226b2e9c-1920x1080.png",
      "background": null,
      "profile_banner": null,
      "profile_banner_background_color": null,
      "partner": true,
      "url": "https://secure.twitch.tv/asiagodtonegg3be0",
      "views": 116095194,
      "followers": 302470,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/asiagodtonegg3be0",
        "follows": "http://api.twitch.tv/kraken/channels/asiagodtonegg3be0/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/asiagodtonegg3be0/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/asiagodtonegg3be0/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/asiagodtonegg3be0",
        "features": "http://api.twitch.tv/kraken/channels/asiagodtonegg3be0/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/asiagodtonegg3be0/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/asiagodtonegg3be0/editors",
        "teams": "http://api.twitch.tv/kraken/channels/asiagodtonegg3be0/teams",
        "videos": "http://api.twitch.tv/kraken/channels/asiagodtonegg3be0/videos"
      }
    }
  }, {
    "_id": 20403403920,
    "game": "League of Legends",
    "viewers": 7697,
    "created_at": "2016-03-24T11:49:15Z",
    "video_height": 1080,
    "average_fps": 60,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/tsm_dyrus"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_tsm_dyrus-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_tsm_dyrus-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_tsm_dyrus-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_tsm_dyrus-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "masters hell ( 7 hour stream)",
      "broadcaster_language": "en",
      "display_name": "TSM_Dyrus",
      "game": "League of Legends",
      "language": "en",
      "_id": 30080751,
      "name": "tsm_dyrus",
      "created_at": "2012-04-27T01:37:07Z",
      "updated_at": "2016-03-24T13:30:19Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/tsm_dyrus-profile_image-65fe199f18b9e0ff-300x300.png",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/tsm_dyrus-channel_offline_image-8de69a5b4e1a593c-1920x1080.png",
      "background": null,
      "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/tsm_dyrus-profile_banner-4f74773e1507d7fc-480.jpeg",
      "profile_banner_background_color": null,
      "partner": true,
      "url": "https://secure.twitch.tv/tsm_dyrus",
      "views": 159664602,
      "followers": 970953,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/tsm_dyrus",
        "follows": "http://api.twitch.tv/kraken/channels/tsm_dyrus/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/tsm_dyrus/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/tsm_dyrus/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/tsm_dyrus",
        "features": "http://api.twitch.tv/kraken/channels/tsm_dyrus/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/tsm_dyrus/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/tsm_dyrus/editors",
        "teams": "http://api.twitch.tv/kraken/channels/tsm_dyrus/teams",
        "videos": "http://api.twitch.tv/kraken/channels/tsm_dyrus/videos"
      }
    }
  }, {
    "_id": 20403591312,
    "game": "Counter-Strike: Global Offensive",
    "viewers": 6006,
    "created_at": "2016-03-24T12:05:48Z",
    "video_height": 720,
    "average_fps": 60.8571428571,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/flusha"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_flusha-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_flusha-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_flusha-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_flusha-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "fnatic flusha",
      "broadcaster_language": "en",
      "display_name": "flusha",
      "game": "Counter-Strike: Global Offensive",
      "language": "sv",
      "_id": 36626799,
      "name": "flusha",
      "created_at": "2012-10-03T23:47:45Z",
      "updated_at": "2016-03-24T13:30:14Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/flusha-profile_image-e92dcef0d14b7d23-300x300.jpeg",
      "banner": null,
      "video_banner": null,
      "background": null,
      "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/flusha-profile_banner-2365166c6cf32578-480.png",
      "profile_banner_background_color": null,
      "partner": true,
      "url": "https://secure.twitch.tv/flusha",
      "views": 1883190,
      "followers": 140818,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/flusha",
        "follows": "http://api.twitch.tv/kraken/channels/flusha/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/flusha/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/flusha/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/flusha",
        "features": "http://api.twitch.tv/kraken/channels/flusha/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/flusha/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/flusha/editors",
        "teams": "http://api.twitch.tv/kraken/channels/flusha/teams",
        "videos": "http://api.twitch.tv/kraken/channels/flusha/videos"
      }
    }
  }, {
    "_id": 20402286944,
    "game": "League of Legends",
    "viewers": 5299,
    "created_at": "2016-03-24T09:59:39Z",
    "video_height": 720,
    "average_fps": 61.0810810811,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/nervarien"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_nervarien-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_nervarien-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_nervarien-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_nervarien-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "NERVARIEN HEXTECH CRAFT \\o/",
      "broadcaster_language": "pl",
      "display_name": "Nervarien",
      "game": "League of Legends",
      "language": "pl",
      "_id": 25452510,
      "name": "nervarien",
      "created_at": "2011-10-14T16:36:04Z",
      "updated_at": "2016-03-24T13:30:02Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/nervarien-profile_image-8a488c78bf3d3082-300x300.png",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/nervarien-channel_offline_image-8b8038246b36a5d6-1920x1080.jpeg",
      "background": null,
      "profile_banner": null,
      "profile_banner_background_color": null,
      "partner": true,
      "url": "https://secure.twitch.tv/nervarien",
      "views": 19403909,
      "followers": 186184,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/nervarien",
        "follows": "http://api.twitch.tv/kraken/channels/nervarien/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/nervarien/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/nervarien/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/nervarien",
        "features": "http://api.twitch.tv/kraken/channels/nervarien/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/nervarien/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/nervarien/editors",
        "teams": "http://api.twitch.tv/kraken/channels/nervarien/teams",
        "videos": "http://api.twitch.tv/kraken/channels/nervarien/videos"
      }
    }
  }, {
    "_id": 20403088624,
    "game": "Counter-Strike: Global Offensive",
    "viewers": 5036,
    "created_at": "2016-03-24T11:20:23Z",
    "video_height": 720,
    "average_fps": 50,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/esl_csgo"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_esl_csgo-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_esl_csgo-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_esl_csgo-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_esl_csgo-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "RERUN: ESL Pro League - EU Matchday 21",
      "broadcaster_language": "en",
      "display_name": "ESL_CSGO",
      "game": "Counter-Strike: Global Offensive",
      "language": "de",
      "_id": 31239503,
      "name": "esl_csgo",
      "created_at": "2012-06-11T13:36:21Z",
      "updated_at": "2016-03-24T13:16:18Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/esl_csgo-profile_image-546a0c1883798a41-300x300.jpeg",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/esl_csgo-channel_offline_image-c9f885982daa1c83-1920x1080.png",
      "background": null,
      "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/esl_csgo-profile_banner-0d10712c29995dc2-480.jpeg",
      "profile_banner_background_color": "#000000",
      "partner": true,
      "url": "https://secure.twitch.tv/esl_csgo",
      "views": 146599446,
      "followers": 1411169,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/esl_csgo",
        "follows": "http://api.twitch.tv/kraken/channels/esl_csgo/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/esl_csgo/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/esl_csgo/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/esl_csgo",
        "features": "http://api.twitch.tv/kraken/channels/esl_csgo/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/esl_csgo/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/esl_csgo/editors",
        "teams": "http://api.twitch.tv/kraken/channels/esl_csgo/teams",
        "videos": "http://api.twitch.tv/kraken/channels/esl_csgo/videos"
      }
    }
  }, {
    "_id": 20401544480,
    "game": "League of Legends",
    "viewers": 4898,
    "created_at": "2016-03-24T08:32:50Z",
    "video_height": 720,
    "average_fps": 30.5714285714,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/riotgames2"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_riotgames2-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_riotgames2-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_riotgames2-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_riotgames2-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "LPL Spring - Week 8 Day 1 ",
      "broadcaster_language": "en",
      "display_name": "RiotGames2",
      "game": "League of Legends",
      "language": "en",
      "_id": 36794584,
      "name": "riotgames2",
      "created_at": "2012-10-09T22:28:27Z",
      "updated_at": "2016-03-24T13:30:16Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/riotgames2-profile_image-951339c7b3adf0e5-300x300.jpeg",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/riotgames2-channel_offline_image-122aecf81f4d28dd-1920x1080.jpeg",
      "background": null,
      "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/riotgames2-profile_banner-1af0451459abe605-480.jpeg",
      "profile_banner_background_color": null,
      "partner": true,
      "url": "https://secure.twitch.tv/riotgames2",
      "views": 24073936,
      "followers": 244618,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/riotgames2",
        "follows": "http://api.twitch.tv/kraken/channels/riotgames2/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/riotgames2/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/riotgames2/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/riotgames2",
        "features": "http://api.twitch.tv/kraken/channels/riotgames2/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/riotgames2/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/riotgames2/editors",
        "teams": "http://api.twitch.tv/kraken/channels/riotgames2/teams",
        "videos": "http://api.twitch.tv/kraken/channels/riotgames2/videos"
      }
    }
  }, {
    "_id": 20403686768,
    "game": "Counter-Strike: Global Offensive",
    "viewers": 4699,
    "created_at": "2016-03-24T12:14:02Z",
    "video_height": 720,
    "average_fps": 60.0100857287,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/ceh9"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_ceh9-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_ceh9-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_ceh9-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_ceh9-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "5 GLOBAL ELITE",
      "broadcaster_language": "ru",
      "display_name": "ceh9",
      "game": "Counter-Strike: Global Offensive",
      "language": "ru",
      "_id": 39176562,
      "name": "ceh9",
      "created_at": "2013-01-09T03:35:12Z",
      "updated_at": "2016-03-24T13:16:14Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/ceh9-profile_image-e0fdbf9505d59164-300x300.png",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/ceh9-channel_offline_image-9e2604e21d87e29c-1920x1080.png",
      "background": null,
      "profile_banner": null,
      "profile_banner_background_color": null,
      "partner": true,
      "url": "https://secure.twitch.tv/ceh9",
      "views": 22658420,
      "followers": 329492,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/ceh9",
        "follows": "http://api.twitch.tv/kraken/channels/ceh9/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/ceh9/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/ceh9/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/ceh9",
        "features": "http://api.twitch.tv/kraken/channels/ceh9/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/ceh9/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/ceh9/editors",
        "teams": "http://api.twitch.tv/kraken/channels/ceh9/teams",
        "videos": "http://api.twitch.tv/kraken/channels/ceh9/videos"
      }
    }
  }, {
    "_id": 20403664016,
    "game": "Hearthstone: Heroes of Warcraft",
    "viewers": 4611,
    "created_at": "2016-03-24T12:12:10Z",
    "video_height": 1080,
    "average_fps": 30,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/roger9527"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_roger9527-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_roger9527-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_roger9527-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_roger9527-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "[Asia] Ahq Roger  亞服 該回去了吧",
      "broadcaster_language": "zh",
      "display_name": "Roger9527",
      "game": "Hearthstone: Heroes of Warcraft",
      "language": "zh-tw",
      "_id": 65653595,
      "name": "roger9527",
      "created_at": "2014-07-05T05:11:49Z",
      "updated_at": "2016-03-24T13:16:12Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/roger9527-profile_image-e6cccadfeba28124-300x300.jpeg",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/roger9527-channel_offline_image-b3b35cec1f8652c7-1920x1080.jpeg",
      "background": null,
      "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/roger9527-profile_banner-41ba859692b0b1ea-480.jpeg",
      "profile_banner_background_color": null,
      "partner": true,
      "url": "https://secure.twitch.tv/roger9527",
      "views": 2184587,
      "followers": 36592,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/roger9527",
        "follows": "http://api.twitch.tv/kraken/channels/roger9527/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/roger9527/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/roger9527/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/roger9527",
        "features": "http://api.twitch.tv/kraken/channels/roger9527/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/roger9527/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/roger9527/editors",
        "teams": "http://api.twitch.tv/kraken/channels/roger9527/teams",
        "videos": "http://api.twitch.tv/kraken/channels/roger9527/videos"
      }
    }
  }, {
    "_id": 20403293712,
    "game": "Counter-Strike: Global Offensive",
    "viewers": 4490,
    "created_at": "2016-03-24T11:39:22Z",
    "video_height": 1080,
    "average_fps": 30.8108108108,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/gocsprotv"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_gocsprotv-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_gocsprotv-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_gocsprotv-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_gocsprotv-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "Приз \"КАЖДЫЙ ЧАС!\" от сайта кейсов GOCS.PRO",
      "broadcaster_language": "ru",
      "display_name": "gocsprotv",
      "game": "Counter-Strike: Global Offensive",
      "language": "ru",
      "_id": 105334309,
      "name": "gocsprotv",
      "created_at": "2015-10-27T17:17:52Z",
      "updated_at": "2016-03-24T13:30:06Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/gocsprotv-profile_image-d93f351e5d835741-300x300.jpeg",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/gocsprotv-channel_offline_image-d6d08ad27c7cc944-1920x1080.jpeg",
      "background": null,
      "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/gocsprotv-profile_banner-10b91abc85e7ea21-480.jpeg",
      "profile_banner_background_color": null,
      "partner": false,
      "url": "https://secure.twitch.tv/gocsprotv",
      "views": 89375,
      "followers": 4065,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/gocsprotv",
        "follows": "http://api.twitch.tv/kraken/channels/gocsprotv/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/gocsprotv/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/gocsprotv/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/gocsprotv",
        "features": "http://api.twitch.tv/kraken/channels/gocsprotv/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/gocsprotv/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/gocsprotv/editors",
        "teams": "http://api.twitch.tv/kraken/channels/gocsprotv/teams",
        "videos": "http://api.twitch.tv/kraken/channels/gocsprotv/videos"
      }
    }
  }, {
    "_id": 20402037120,
    "game": "RuneScape",
    "viewers": 4226,
    "created_at": "2016-03-24T09:31:23Z",
    "video_height": 720,
    "average_fps": 60,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/purespam"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_purespam-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_purespam-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_purespam-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_purespam-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "!death Shoutcasting DMM Tournament Finale This Saturday ~ @ianspam (Twitter/YouTube) !newvid !snapchat",
      "broadcaster_language": "en",
      "display_name": "PureSpam",
      "game": "RuneScape",
      "language": "en",
      "_id": 29273855,
      "name": "purespam",
      "created_at": "2012-03-25T17:50:11Z",
      "updated_at": "2016-03-24T13:30:12Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/purespam-profile_image-4e63541a59b8d058-300x300.jpeg",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/purespam-channel_offline_image-f7b84baec57e05d6-1920x1080.jpeg",
      "background": null,
      "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/purespam-profile_banner-1388074d36d5180e-480.jpeg",
      "profile_banner_background_color": null,
      "partner": true,
      "url": "https://secure.twitch.tv/purespam",
      "views": 1858225,
      "followers": 37402,
      "_links": {
        "self": "https://api.twitch.tv/kraken/channels/purespam",
        "follows": "https://api.twitch.tv/kraken/channels/purespam/follows",
        "commercial": "https://api.twitch.tv/kraken/channels/purespam/commercial",
        "stream_key": "https://api.twitch.tv/kraken/channels/purespam/stream_key",
        "chat": "https://api.twitch.tv/kraken/chat/purespam",
        "features": "https://api.twitch.tv/kraken/channels/purespam/features",
        "subscriptions": "https://api.twitch.tv/kraken/channels/purespam/subscriptions",
        "editors": "https://api.twitch.tv/kraken/channels/purespam/editors",
        "teams": "https://api.twitch.tv/kraken/channels/purespam/teams",
        "videos": "https://api.twitch.tv/kraken/channels/purespam/videos"
      }
    }
  }, {
    "_id": 20403598720,
    "game": "Hearthstone: Heroes of Warcraft",
    "viewers": 3980,
    "created_at": "2016-03-24T12:06:26Z",
    "video_height": 720,
    "average_fps": 30.0075018755,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/milleniumtvhs"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_milleniumtvhs-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_milleniumtvhs-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_milleniumtvhs-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_milleniumtvhs-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "[Fr] Marathon Torlk 13h-00h ! ",
      "broadcaster_language": "fr",
      "display_name": "MilleniumTVHS",
      "game": "Hearthstone: Heroes of Warcraft",
      "language": "fr",
      "_id": 88398452,
      "name": "milleniumtvhs",
      "created_at": "2015-04-12T22:11:37Z",
      "updated_at": "2016-03-24T13:30:46Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/milleniumtvhs-profile_image-1c57dacd088f7700-300x300.png",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/milleniumtvhs-channel_offline_image-8fe56d970fce458f-1920x1080.png",
      "background": null,
      "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/milleniumtvhs-profile_banner-b0996e7bc88ba494-480.png",
      "profile_banner_background_color": null,
      "partner": true,
      "url": "https://secure.twitch.tv/milleniumtvhs",
      "views": 9868339,
      "followers": 56147,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/milleniumtvhs",
        "follows": "http://api.twitch.tv/kraken/channels/milleniumtvhs/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/milleniumtvhs/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/milleniumtvhs/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/milleniumtvhs",
        "features": "http://api.twitch.tv/kraken/channels/milleniumtvhs/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/milleniumtvhs/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/milleniumtvhs/editors",
        "teams": "http://api.twitch.tv/kraken/channels/milleniumtvhs/teams",
        "videos": "http://api.twitch.tv/kraken/channels/milleniumtvhs/videos"
      }
    }
  }, {
    "_id": 20402676736,
    "game": "Hearthstone: Heroes of Warcraft",
    "viewers": 3616,
    "created_at": "2016-03-24T10:40:48Z",
    "video_height": 1080,
    "average_fps": 60.0100857287,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/meleeman777"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_meleeman777-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_meleeman777-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_meleeman777-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_meleeman777-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "Идем в Топ 100! (Ведьмак в 21:00) продажный день, треки-100р",
      "broadcaster_language": "ru",
      "display_name": "Meleeman777",
      "game": "Hearthstone: Heroes of Warcraft",
      "language": "ru",
      "_id": 55716275,
      "name": "meleeman777",
      "created_at": "2014-01-28T13:14:48Z",
      "updated_at": "2016-03-24T13:30:08Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/meleeman777-profile_image-b935c8332585f907-300x300.png",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/meleeman777-channel_offline_image-033d1da95d9b54e8-1920x1080.png",
      "background": null,
      "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/meleeman777-profile_banner-6ca47800dd3d2644-480.png",
      "profile_banner_background_color": "#ffffff",
      "partner": true,
      "url": "https://secure.twitch.tv/meleeman777",
      "views": 2048842,
      "followers": 45769,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/meleeman777",
        "follows": "http://api.twitch.tv/kraken/channels/meleeman777/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/meleeman777/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/meleeman777/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/meleeman777",
        "features": "http://api.twitch.tv/kraken/channels/meleeman777/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/meleeman777/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/meleeman777/editors",
        "teams": "http://api.twitch.tv/kraken/channels/meleeman777/teams",
        "videos": "http://api.twitch.tv/kraken/channels/meleeman777/videos"
      }
    }
  }, {
    "_id": 20397022272,
    "game": "Tom Clancy's The Division",
    "viewers": 3595,
    "created_at": "2016-03-24T01:41:59Z",
    "video_height": 1080,
    "average_fps": 30.0283286119,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/streamerhouse"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_streamerhouse-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_streamerhouse-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_streamerhouse-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_streamerhouse-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "☣ New !patch ☣ 1000HR MARATHON ☣ Claim Your Gear !agent  [ 24/7 GAMING SINCE 2013 ][ TEAM !ORIGIN ][ TEAM !NVIDIA ]",
      "broadcaster_language": "en",
      "display_name": "StreamerHouse",
      "game": "Tom Clancy's The Division",
      "language": "en",
      "_id": 44741426,
      "name": "streamerhouse",
      "created_at": "2013-06-14T15:50:41Z",
      "updated_at": "2016-03-24T13:16:20Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/streamerhouse-profile_image-ef307bd1a40c75b1-300x300.png",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/streamerhouse-channel_offline_image-643a63b6ee788b02-1920x1080.jpeg",
      "background": null,
      "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/streamerhouse-profile_banner-bf842b59fd9e7bb8-480.png",
      "profile_banner_background_color": null,
      "partner": true,
      "url": "https://secure.twitch.tv/streamerhouse",
      "views": 41144843,
      "followers": 435965,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/streamerhouse",
        "follows": "http://api.twitch.tv/kraken/channels/streamerhouse/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/streamerhouse/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/streamerhouse/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/streamerhouse",
        "features": "http://api.twitch.tv/kraken/channels/streamerhouse/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/streamerhouse/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/streamerhouse/editors",
        "teams": "http://api.twitch.tv/kraken/channels/streamerhouse/teams",
        "videos": "http://api.twitch.tv/kraken/channels/streamerhouse/videos"
      }
    }
  }, {
    "_id": 20402315920,
    "game": "Counter-Strike: Global Offensive",
    "viewers": 3405,
    "created_at": "2016-03-24T10:02:48Z",
    "video_height": 614,
    "average_fps": 30.806321993,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/girlstorule"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_girlstorule-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_girlstorule-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_girlstorule-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_girlstorule-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "НОВЫЕ СМАЙЛЫ! - Играй с девушками на CSGO1.COM - Поймай удачу и сорви джекпот!",
      "broadcaster_language": "ru",
      "display_name": "GirlsToRule",
      "game": "Counter-Strike: Global Offensive",
      "language": "ru",
      "_id": 77730446,
      "name": "girlstorule",
      "created_at": "2014-12-22T15:23:35Z",
      "updated_at": "2016-03-24T13:16:21Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/girlstorule-profile_image-bdaf086d1ee91f6a-300x300.jpeg",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/girlstorule-channel_offline_image-00069b818d8c4484-1920x1080.jpeg",
      "background": null,
      "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/girlstorule-profile_banner-fa7caef8820a2b23-480.png",
      "profile_banner_background_color": "#ffffff",
      "partner": true,
      "url": "https://secure.twitch.tv/girlstorule",
      "views": 6320057,
      "followers": 178388,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/girlstorule",
        "follows": "http://api.twitch.tv/kraken/channels/girlstorule/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/girlstorule/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/girlstorule/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/girlstorule",
        "features": "http://api.twitch.tv/kraken/channels/girlstorule/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/girlstorule/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/girlstorule/editors",
        "teams": "http://api.twitch.tv/kraken/channels/girlstorule/teams",
        "videos": "http://api.twitch.tv/kraken/channels/girlstorule/videos"
      }
    }
  }, {
    "_id": 20402424608,
    "game": "Counter-Strike: Global Offensive",
    "viewers": 3314,
    "created_at": "2016-03-24T10:14:05Z",
    "video_height": 1080,
    "average_fps": 30.0150075038,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/massansc"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_massansc-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_massansc-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_massansc-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_massansc-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "Betting, Giveaways, Noob Games!",
      "broadcaster_language": "en",
      "display_name": "MaSsanSC",
      "game": "Counter-Strike: Global Offensive",
      "language": "en",
      "_id": 31665430,
      "name": "massansc",
      "created_at": "2012-06-27T04:50:14Z",
      "updated_at": "2016-03-24T13:30:29Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/massansc-profile_image-fbb911c2ff0395ec-300x300.png",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/massansc-channel_offline_image-e00861f551cd6592-1920x1080.png",
      "background": null,
      "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/massansc-profile_banner-a1d2be4d6b603dab-480.png",
      "profile_banner_background_color": null,
      "partner": true,
      "url": "https://secure.twitch.tv/massansc",
      "views": 22409170,
      "followers": 296607,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/massansc",
        "follows": "http://api.twitch.tv/kraken/channels/massansc/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/massansc/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/massansc/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/massansc",
        "features": "http://api.twitch.tv/kraken/channels/massansc/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/massansc/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/massansc/editors",
        "teams": "http://api.twitch.tv/kraken/channels/massansc/teams",
        "videos": "http://api.twitch.tv/kraken/channels/massansc/videos"
      }
    }
  }, {
    "_id": 20404074320,
    "game": "League of Legends",
    "viewers": 3213,
    "created_at": "2016-03-24T12:47:22Z",
    "video_height": 1080,
    "average_fps": 60.0276625173,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/mushisgosu"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_mushisgosu-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_mushisgosu-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_mushisgosu-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_mushisgosu-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "TSM Gosu - fixing sleep schedule WutFace",
      "broadcaster_language": "en",
      "display_name": "MushIsGosu",
      "game": "League of Legends",
      "language": "en",
      "_id": 41939266,
      "name": "mushisgosu",
      "created_at": "2013-03-31T21:12:14Z",
      "updated_at": "2016-03-24T13:16:18Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/mushisgosu-profile_image-b1c8bb5fd700025e-300x300.png",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/mushisgosu-channel_offline_image-7e3401b20cb5d739-1920x1080.png",
      "background": null,
      "profile_banner": null,
      "profile_banner_background_color": null,
      "partner": true,
      "url": "https://secure.twitch.tv/mushisgosu",
      "views": 63462679,
      "followers": 906128,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/mushisgosu",
        "follows": "http://api.twitch.tv/kraken/channels/mushisgosu/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/mushisgosu/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/mushisgosu/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/mushisgosu",
        "features": "http://api.twitch.tv/kraken/channels/mushisgosu/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/mushisgosu/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/mushisgosu/editors",
        "teams": "http://api.twitch.tv/kraken/channels/mushisgosu/teams",
        "videos": "http://api.twitch.tv/kraken/channels/mushisgosu/videos"
      }
    }
  }, {
    "_id": 20402105648,
    "game": "Hearthstone: Heroes of Warcraft",
    "viewers": 3159,
    "created_at": "2016-03-24T09:39:16Z",
    "video_height": 1080,
    "average_fps": 30,
    "delay": 0,
    "is_playlist": false,
    "_links": {
      "self": "https://api.twitch.tv/kraken/streams/eloise_ailv"
    },
    "preview": {
      "small": "https://static-cdn.jtvnw.net/previews-ttv/live_user_eloise_ailv-80x45.jpg",
      "medium": "https://static-cdn.jtvnw.net/previews-ttv/live_user_eloise_ailv-320x180.jpg",
      "large": "https://static-cdn.jtvnw.net/previews-ttv/live_user_eloise_ailv-640x360.jpg",
      "template": "https://static-cdn.jtvnw.net/previews-ttv/live_user_eloise_ailv-{width}x{height}.jpg"
    },
    "channel": {
      "mature": false,
      "status": "mrdistruction taking over the planet wutface!  my youtube highlight: https://www.youtube.com/EloiseHS",
      "broadcaster_language": "en",
      "display_name": "eloise_ailv",
      "game": "Hearthstone: Heroes of Warcraft",
      "language": "zh-cn",
      "_id": 85909658,
      "name": "eloise_ailv",
      "created_at": "2015-03-23T12:29:16Z",
      "updated_at": "2016-03-24T13:30:11Z",
      "delay": null,
      "logo": "https://static-cdn.jtvnw.net/jtv_user_pictures/eloise_ailv-profile_image-9554ac2957f19a51-300x300.png",
      "banner": null,
      "video_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/eloise_ailv-channel_offline_image-ada57dabb2583e31-1920x1080.jpeg",
      "background": null,
      "profile_banner": "https://static-cdn.jtvnw.net/jtv_user_pictures/eloise_ailv-profile_banner-b16fe1a4d11481ef-480.jpeg",
      "profile_banner_background_color": null,
      "partner": true,
      "url": "https://secure.twitch.tv/eloise_ailv",
      "views": 2716360,
      "followers": 156774,
      "_links": {
        "self": "http://api.twitch.tv/kraken/channels/eloise_ailv",
        "follows": "http://api.twitch.tv/kraken/channels/eloise_ailv/follows",
        "commercial": "http://api.twitch.tv/kraken/channels/eloise_ailv/commercial",
        "stream_key": "http://api.twitch.tv/kraken/channels/eloise_ailv/stream_key",
        "chat": "http://api.twitch.tv/kraken/chat/eloise_ailv",
        "features": "http://api.twitch.tv/kraken/channels/eloise_ailv/features",
        "subscriptions": "http://api.twitch.tv/kraken/channels/eloise_ailv/subscriptions",
        "editors": "http://api.twitch.tv/kraken/channels/eloise_ailv/editors",
        "teams": "http://api.twitch.tv/kraken/channels/eloise_ailv/teams",
        "videos": "http://api.twitch.tv/kraken/channels/eloise_ailv/videos"
      }
    }
  }],
  "_total": 14915,
  "_links": {
    "self": "https://api.twitch.tv/kraken/streams?limit=25\u0026offset=0",
    "next": "https://api.twitch.tv/kraken/streams?limit=25\u0026offset=25",
    "featured": "https://api.twitch.tv/kraken/streams/featured",
    "summary": "https://api.twitch.tv/kraken/streams/summary",
    "followed": "https://api.twitch.tv/kraken/streams/followed"
  }
});
